name: Lint

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:

env:
  CARGO_TERM_COLOR: always

jobs:
  style:
    name: Check Style

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1

      - name: Cache cargo registry
        uses: Swatinem/rust-cache@v2

      - name: Cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Install clippy-sarif and sarif-fmt
        run: cargo install clippy-sarif sarif-fmt --locked --git https://github.com/psastras/sarif-rs.git --rev 11c33a53f6ffeaed736856b86fb6b7b09fabdfd8

      - name: Cargo clippy
        run: cargo clippy --all-features --tests --message-format=json |
          clippy-sarif | tee clippy_result.sarif | sarif-fmt
        env:
          RUSTFLAGS: "-D warnings"

      - name: Upload Clippy results to GitHub
        uses: github/codeql-action/upload-sarif@d39d31e687223d841ef683f52467bd88e9b21c14 # v3.25.3
        with:
          sarif_file: clippy_result.sarif
